
package mypackage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZL_InformationServiceSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZLInformationServiceSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetOracleSysDate", action = "http://tempuri.org/GetOracleSysDate")
    @WebResult(name = "GetOracleSysDateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetOracleSysDate", targetNamespace = "http://tempuri.org/", className = "mypackage.GetOracleSysDate")
    @ResponseWrapper(localName = "GetOracleSysDateResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.GetOracleSysDateResponse")
    public String getOracleSysDate();

    /**
     * 
     * @param reData
     * @return
     *     returns mypackage.OutPatientResponse.OutPatientResult
     */
    @WebMethod(operationName = "OutPatient", action = "http://tempuri.org/OutPatient")
    @WebResult(name = "OutPatientResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "OutPatient", targetNamespace = "http://tempuri.org/", className = "mypackage.OutPatient")
    @ResponseWrapper(localName = "OutPatientResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.OutPatientResponse")
    public mypackage.OutPatientResponse.OutPatientResult outPatient(
        @WebParam(name = "ReData", targetNamespace = "http://tempuri.org/")
        String reData);

    /**
     * 
     * @param reData
     * @return
     *     returns mypackage.HospitalizationResponse.HospitalizationResult
     */
    @WebMethod(operationName = "Hospitalization", action = "http://tempuri.org/Hospitalization")
    @WebResult(name = "HospitalizationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Hospitalization", targetNamespace = "http://tempuri.org/", className = "mypackage.Hospitalization")
    @ResponseWrapper(localName = "HospitalizationResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.HospitalizationResponse")
    public mypackage.HospitalizationResponse.HospitalizationResult hospitalization(
        @WebParam(name = "ReData", targetNamespace = "http://tempuri.org/")
        String reData);

    /**
     * 
     * @param reData
     * @return
     *     returns mypackage.MedicalTechnologyResponse.MedicalTechnologyResult
     */
    @WebMethod(operationName = "MedicalTechnology", action = "http://tempuri.org/MedicalTechnology")
    @WebResult(name = "MedicalTechnologyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "MedicalTechnology", targetNamespace = "http://tempuri.org/", className = "mypackage.MedicalTechnology")
    @ResponseWrapper(localName = "MedicalTechnologyResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.MedicalTechnologyResponse")
    public mypackage.MedicalTechnologyResponse.MedicalTechnologyResult medicalTechnology(
        @WebParam(name = "ReData", targetNamespace = "http://tempuri.org/")
        String reData);

    /**
     * 
     * @param reData
     * @return
     *     returns mypackage.PhysicalExaminationResponse.PhysicalExaminationResult
     */
    @WebMethod(operationName = "PhysicalExamination", action = "http://tempuri.org/PhysicalExamination")
    @WebResult(name = "PhysicalExaminationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "PhysicalExamination", targetNamespace = "http://tempuri.org/", className = "mypackage.PhysicalExamination")
    @ResponseWrapper(localName = "PhysicalExaminationResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.PhysicalExaminationResponse")
    public mypackage.PhysicalExaminationResponse.PhysicalExaminationResult physicalExamination(
        @WebParam(name = "ReData", targetNamespace = "http://tempuri.org/")
        String reData);

    /**
     * 
     * @param reData
     * @return
     *     returns mypackage.UserManagerResponse.UserManagerResult
     */
    @WebMethod(operationName = "UserManager", action = "http://tempuri.org/UserManager")
    @WebResult(name = "UserManagerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UserManager", targetNamespace = "http://tempuri.org/", className = "mypackage.UserManager")
    @ResponseWrapper(localName = "UserManagerResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.UserManagerResponse")
    public mypackage.UserManagerResponse.UserManagerResult userManager(
        @WebParam(name = "ReData", targetNamespace = "http://tempuri.org/")
        String reData);

    /**
     * 
     * @param reData
     * @return
     *     returns mypackage.InformationResponse.InformationResult
     */
    @WebMethod(operationName = "Information", action = "http://tempuri.org/Information")
    @WebResult(name = "InformationResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Information", targetNamespace = "http://tempuri.org/", className = "mypackage.Information")
    @ResponseWrapper(localName = "InformationResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.InformationResponse")
    public mypackage.InformationResponse.InformationResult information(
        @WebParam(name = "ReData", targetNamespace = "http://tempuri.org/")
        String reData);

    /**
     * 
     * @param reData
     * @return
     *     returns mypackage.CustomResponse.CustomResult
     */
    @WebMethod(operationName = "Custom", action = "http://tempuri.org/Custom")
    @WebResult(name = "CustomResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Custom", targetNamespace = "http://tempuri.org/", className = "mypackage.Custom")
    @ResponseWrapper(localName = "CustomResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.CustomResponse")
    public mypackage.CustomResponse.CustomResult custom(
        @WebParam(name = "ReData", targetNamespace = "http://tempuri.org/")
        String reData);

    /**
     * 
     * @param reData
     * @return
     *     returns mypackage.InsideBasicResponse.InsideBasicResult
     */
    @WebMethod(operationName = "InsideBasic", action = "http://tempuri.org/InsideBasic")
    @WebResult(name = "InsideBasicResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "InsideBasic", targetNamespace = "http://tempuri.org/", className = "mypackage.InsideBasic")
    @ResponseWrapper(localName = "InsideBasicResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.InsideBasicResponse")
    public mypackage.InsideBasicResponse.InsideBasicResult insideBasic(
        @WebParam(name = "ReData", targetNamespace = "http://tempuri.org/")
        String reData);

    /**
     * 
     * @param reData
     * @return
     *     returns mypackage.InsideResponse.InsideResult
     */
    @WebMethod(operationName = "Inside", action = "http://tempuri.org/Inside")
    @WebResult(name = "InsideResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "Inside", targetNamespace = "http://tempuri.org/", className = "mypackage.Inside")
    @ResponseWrapper(localName = "InsideResponse", targetNamespace = "http://tempuri.org/", className = "mypackage.InsideResponse")
    public mypackage.InsideResponse.InsideResult inside(
        @WebParam(name = "ReData", targetNamespace = "http://tempuri.org/")
        String reData);

}
