
package mypackage;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZL_InformationService", targetNamespace = "http://tempuri.org/", wsdlLocation = "file:///Users/zbs/Desktop/hpx10.wsdl")
public class ZLInformationService
    extends Service
{

    private final static URL ZLINFORMATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ZLINFORMATIONSERVICE_EXCEPTION;
    private final static QName ZLINFORMATIONSERVICE_QNAME = new QName("http://tempuri.org/", "ZL_InformationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:///Users/zbs/Desktop/hpx10.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZLINFORMATIONSERVICE_WSDL_LOCATION = url;
        ZLINFORMATIONSERVICE_EXCEPTION = e;
    }

    public ZLInformationService() {
        super(__getWsdlLocation(), ZLINFORMATIONSERVICE_QNAME);
    }

    public ZLInformationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZLINFORMATIONSERVICE_QNAME, features);
    }

    public ZLInformationService(URL wsdlLocation) {
        super(wsdlLocation, ZLINFORMATIONSERVICE_QNAME);
    }

    public ZLInformationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZLINFORMATIONSERVICE_QNAME, features);
    }

    public ZLInformationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZLInformationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZLInformationServiceSoap
     */
    @WebEndpoint(name = "ZL_InformationServiceSoap")
    public ZLInformationServiceSoap getZLInformationServiceSoap() {
        return super.getPort(new QName("http://tempuri.org/", "ZL_InformationServiceSoap"), ZLInformationServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZLInformationServiceSoap
     */
    @WebEndpoint(name = "ZL_InformationServiceSoap")
    public ZLInformationServiceSoap getZLInformationServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ZL_InformationServiceSoap"), ZLInformationServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ZLInformationServiceSoap
     */
    @WebEndpoint(name = "ZL_InformationServiceSoap12")
    public ZLInformationServiceSoap getZLInformationServiceSoap12() {
        return super.getPort(new QName("http://tempuri.org/", "ZL_InformationServiceSoap12"), ZLInformationServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZLInformationServiceSoap
     */
    @WebEndpoint(name = "ZL_InformationServiceSoap12")
    public ZLInformationServiceSoap getZLInformationServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ZL_InformationServiceSoap12"), ZLInformationServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns ZLInformationServiceHttpGet
     */
    @WebEndpoint(name = "ZL_InformationServiceHttpGet")
    public ZLInformationServiceHttpGet getZLInformationServiceHttpGet() {
        return super.getPort(new QName("http://tempuri.org/", "ZL_InformationServiceHttpGet"), ZLInformationServiceHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZLInformationServiceHttpGet
     */
    @WebEndpoint(name = "ZL_InformationServiceHttpGet")
    public ZLInformationServiceHttpGet getZLInformationServiceHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ZL_InformationServiceHttpGet"), ZLInformationServiceHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns ZLInformationServiceHttpPost
     */
    @WebEndpoint(name = "ZL_InformationServiceHttpPost")
    public ZLInformationServiceHttpPost getZLInformationServiceHttpPost() {
        return super.getPort(new QName("http://tempuri.org/", "ZL_InformationServiceHttpPost"), ZLInformationServiceHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZLInformationServiceHttpPost
     */
    @WebEndpoint(name = "ZL_InformationServiceHttpPost")
    public ZLInformationServiceHttpPost getZLInformationServiceHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "ZL_InformationServiceHttpPost"), ZLInformationServiceHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZLINFORMATIONSERVICE_EXCEPTION!= null) {
            throw ZLINFORMATIONSERVICE_EXCEPTION;
        }
        return ZLINFORMATIONSERVICE_WSDL_LOCATION;
    }

}
