server:
    port: 50002
    # 统一接口访问前缀
    servlet-path: /reservation

management:
    address: 127.0.0.1
mybatis:
    my:
        beanPath: com.jishi.reservation.dao.models
        mapperXmlPath: classpath:mapper/*.xml
        mapperPath: com.jishi.reservation.dao.mapper


constant:
    dynamic_code_key:
        login_or_register: login_or_register
        change_phone_origin: change_phone_origin
        change_phone_new: change_phone_new

#开发环境
---
spring:
    profiles:
        active: dev
    datasource:
        beanPath: com.jishi.reservation.dao.models
        mapperXmlPath: classpath:mapper/*.xml
        mapperPath: com.jishi.reservation.dao.mapper
        master:
            name: ReadAndWrite
            url: jdbc:mysql://182.92.78.118:3306/his?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: root
        slave1:
            name: ReadAndWrite
            url: jdbc:mysql://182.92.78.118:3306/his?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: root
redis:
    host: 119.29.108.150
    port: 6379

#测试环境
---
spring:
    profiles:
        active: test
    datasource:
        beanPath: com.jishi.reservation.dao.models
        mapperXmlPath: classpath:mapper/*.xml
        mapperPath: com.jishi.reservation.dao.mapper
        master:
            name: ReadAndWrite
            url: jdbc:mysql://182.92.78.118:3306/his?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: root
        slave1:
            name: ReadAndWrite
            url: jdbc:mysql://182.92.78.118:3306/his?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: root
redis:
    host: 119.29.108.150
    port: 6379

#线上正式环境
---
spring:
    profiles:
        active: pro
    datasource:
        beanPath: com.jishi.reservation.dao.models
        mapperXmlPath: classpath:mapper/*.xml
        mapperPath: com.jishi.reservation.dao.mapper
        master:
            name: ReadAndWrite
            url: jdbc:mysql://rm-wz96u1z25sua002ln.mysql.rds.aliyuncs.com:3306/jinxinapp?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: root
        slave1:
            name: ReadAndWrite
            url: jdbc:mysql://rm-wz96u1z25sua002ln.mysql.rds.aliyuncs.com:3306/jinxinapp?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: root
# 等待新的
redis:
    host: 119.29.108.150
    port: 6379
